### PR TITLE
Fixed parsing query components with embedded question marks (with test)

### PR DESCRIPTION
**Pull request by tuffnatty**

### CODE REVIEW

**Comment by tuffnatty** [comment]
This seems to be code duplicated from Urlly (?), so probably the fix should end up there as well.

**Comment by tuffnatty** [comment]
And Rowdy does it, too.

**Comment by guzba** [comment]
> The query component is indicated by the first question mark ("?") character

https://www.rfc-editor.org/rfc/rfc3986#section-3.4

So this should be good to fix.

**Comment by treeform** [comment]
Thank you for the PR!

**Pull request merged**
